Inventory
ZuhabWasim/ReflectionGame pull request #29
Opened 2022-02-21 01:16 UTC by Flryang

Added 2d assets for the inventory

2022-02-21 23:29 UTC, ZuhabWasim commented on Assets/Scripts/Inventory.cs
>                  PlayerController.PlaySound( "object_obtained" );
These will be changed to incorporate Lakshya's new AudioPlayer instead

2022-02-21 23:33 UTC, ZuhabWasim requested changes
Looks good Meilin! There will be a few changes you'll need to implement following Lakshya's overhaul of the audio system so once that's merged, let's incorporate those changes and have this merged too.

Also for the image files, would you be able to rename them to follow the naming conventions recently in [guidelines.md](https://github.com/ZuhabWasim/ReflectionGame/blob/main/guidelines.md)? So instead of `Inventory_Gear (Unmoving Piece) FINAL.png` we'd have `inventory_gear_unmoving_piece.png`

2022-02-23 07:54 UTC, ZuhabWasim approved these changes
Looks good to me. Looks like the Camera Mirror Position script was not attached to the mirrors as before so we added it back to the prefab. Looks like it's fine now

Additionally, looks like the only error observable is that copy-pasting the present world copied the script for the vanity mirror so both the past and present are caching an audio source at the same key, causing the audio to not play. Solution, disable the script in VanityMirrorPast

2022-02-23 08:05 UTC, Flryang commented
Somehow me and Zuhab cannot rebase and merge this branch to main. Could you please take a look at this and see if you are able to rebase? Thanks @Lakshya2610 @dargonfyl

2022-02-24 03:55 UTC, dargonfyl commented
GitHub says that it can automatically merge, but I'm going to try to rebase for now.

2022-02-24 05:51 UTC, dargonfyl approved these changes

2022-02-24 05:52 UTC, merged