added interaction icons
ZuhabWasim/ReflectionGame pull request #42
Opened 2022-03-03 23:08 UTC by Flryang

modified the prefab UI_canvas and added icons to the bottom right corner, which will display a hand icon whenever the target object is of type MOVE, PICKUP, OPEN, CLOSE and will display an eye icon whenever the target object is of type INTERACT, and will display a reflection icon whenever the player is able to teleport, otherwise it should be hidden.

2022-03-05 05:33 UTC, ZuhabWasim approved these changes

2022-03-06 02:12 UTC, Lakshya2610 requested changes
Looks good, there are some styling issues that need to be fixed (check comments). After that it should be good to merge

2022-03-06 02:12 UTC, Lakshya2610 commented on Assets/Scripts/PlayerController.cs
> +    void showInteractionIcon()
Can you follow the style convention for naming functions. It should be `ShowInteractionIcon`

2022-03-06 02:12 UTC, Lakshya2610 commented on Assets/Scripts/PlayerController.cs
> +        interactionIcon = GameObject.Find("UI_Canvas").GetComponents<InteractionIcon>()[0];
Create a string in Globals for "UI_Canvas" and replace this & other instances. Having raw strings in script is against the style convention we're following

2022-03-06 02:12 UTC, Lakshya2610 commented on Assets/Scripts/UIElements/InteractionIcon.cs
> +    public void showReflectionIcon()
Same style error with function names in this script as well. Function names should start with capital letter

2022-03-06 07:23 UTC, merged